[project]
name = 'interplanetary-commerce-protocol'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.orbital-logistics-coordinator]
path = 'contracts/orbital-logistics-coordinator.clar'
clarity_version = 3
epoch = 3.1

[contracts.time-delayed-transaction-processor]
path = 'contracts/time-delayed-transaction-processor.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
